name: Issue
description: Standard issue template
title: ''
labels: []
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Issue description
    validations:
      required: true

  - type: textarea
    id: original-user-prompt
    attributes:
      label: Original user prompt
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      value: |
        - [ ]
        - [ ]
    validations:
      required: true
